/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { NubariumOtherValidationService } from "../nubariumOtherValidation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NubariumOtherValidationCreateInput } from "./NubariumOtherValidationCreateInput";
import { NubariumOtherValidation } from "./NubariumOtherValidation";
import { NubariumOtherValidationFindManyArgs } from "./NubariumOtherValidationFindManyArgs";
import { NubariumOtherValidationWhereUniqueInput } from "./NubariumOtherValidationWhereUniqueInput";
import { NubariumOtherValidationUpdateInput } from "./NubariumOtherValidationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class NubariumOtherValidationControllerBase {
  constructor(
    protected readonly service: NubariumOtherValidationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: NubariumOtherValidation })
  @nestAccessControl.UseRoles({
    resource: "NubariumOtherValidation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createNubariumOtherValidation(
    @common.Body() data: NubariumOtherValidationCreateInput
  ): Promise<NubariumOtherValidation> {
    return await this.service.createNubariumOtherValidation({
      data: data,
      select: {
        correlationId: true,
        correo: true,
        customerId: true,
        eaAdvice: true,
        eaAdviceId: true,
        eaReason: true,
        eaReasonId: true,
        eaRiskBand: true,
        eaRiskBandId: true,
        eaScore: true,
        eaStatusId: true,
        fechaRegistro: true,
        fraudRisk: true,
        fraudType: true,
        id: true,
        telefono: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [NubariumOtherValidation] })
  @ApiNestedQuery(NubariumOtherValidationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "NubariumOtherValidation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async nubariumOtherValidations(
    @common.Req() request: Request
  ): Promise<NubariumOtherValidation[]> {
    const args = plainToClass(
      NubariumOtherValidationFindManyArgs,
      request.query
    );
    return this.service.nubariumOtherValidations({
      ...args,
      select: {
        correlationId: true,
        correo: true,
        customerId: true,
        eaAdvice: true,
        eaAdviceId: true,
        eaReason: true,
        eaReasonId: true,
        eaRiskBand: true,
        eaRiskBandId: true,
        eaScore: true,
        eaStatusId: true,
        fechaRegistro: true,
        fraudRisk: true,
        fraudType: true,
        id: true,
        telefono: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: NubariumOtherValidation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NubariumOtherValidation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async nubariumOtherValidation(
    @common.Param() params: NubariumOtherValidationWhereUniqueInput
  ): Promise<NubariumOtherValidation | null> {
    const result = await this.service.nubariumOtherValidation({
      where: params,
      select: {
        correlationId: true,
        correo: true,
        customerId: true,
        eaAdvice: true,
        eaAdviceId: true,
        eaReason: true,
        eaReasonId: true,
        eaRiskBand: true,
        eaRiskBandId: true,
        eaScore: true,
        eaStatusId: true,
        fechaRegistro: true,
        fraudRisk: true,
        fraudType: true,
        id: true,
        telefono: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: NubariumOtherValidation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NubariumOtherValidation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateNubariumOtherValidation(
    @common.Param() params: NubariumOtherValidationWhereUniqueInput,
    @common.Body() data: NubariumOtherValidationUpdateInput
  ): Promise<NubariumOtherValidation | null> {
    try {
      return await this.service.updateNubariumOtherValidation({
        where: params,
        data: data,
        select: {
          correlationId: true,
          correo: true,
          customerId: true,
          eaAdvice: true,
          eaAdviceId: true,
          eaReason: true,
          eaReasonId: true,
          eaRiskBand: true,
          eaRiskBandId: true,
          eaScore: true,
          eaStatusId: true,
          fechaRegistro: true,
          fraudRisk: true,
          fraudType: true,
          id: true,
          telefono: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: NubariumOtherValidation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NubariumOtherValidation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteNubariumOtherValidation(
    @common.Param() params: NubariumOtherValidationWhereUniqueInput
  ): Promise<NubariumOtherValidation | null> {
    try {
      return await this.service.deleteNubariumOtherValidation({
        where: params,
        select: {
          correlationId: true,
          correo: true,
          customerId: true,
          eaAdvice: true,
          eaAdviceId: true,
          eaReason: true,
          eaReasonId: true,
          eaRiskBand: true,
          eaRiskBandId: true,
          eaScore: true,
          eaStatusId: true,
          fechaRegistro: true,
          fraudRisk: true,
          fraudType: true,
          id: true,
          telefono: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
