/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ModifiedSalesclerkService } from "../modifiedSalesclerk.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ModifiedSalesclerkCreateInput } from "./ModifiedSalesclerkCreateInput";
import { ModifiedSalesclerk } from "./ModifiedSalesclerk";
import { ModifiedSalesclerkFindManyArgs } from "./ModifiedSalesclerkFindManyArgs";
import { ModifiedSalesclerkWhereUniqueInput } from "./ModifiedSalesclerkWhereUniqueInput";
import { ModifiedSalesclerkUpdateInput } from "./ModifiedSalesclerkUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ModifiedSalesclerkControllerBase {
  constructor(
    protected readonly service: ModifiedSalesclerkService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ModifiedSalesclerk })
  @nestAccessControl.UseRoles({
    resource: "ModifiedSalesclerk",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createModifiedSalesclerk(
    @common.Body() data: ModifiedSalesclerkCreateInput
  ): Promise<ModifiedSalesclerk> {
    return await this.service.createModifiedSalesclerk({
      data: {
        ...data,

        financedSales: data.financedSales
          ? {
              connect: data.financedSales,
            }
          : undefined,
      },
      select: {
        financedSales: {
          select: {
            id: true,
          },
        },

        id: true,
        newSalesclerkUserId: true,
        oldSalesclerkUserId: true,
        personalLoanId: true,
        updatedAt: true,
        updatedUserId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ModifiedSalesclerk] })
  @ApiNestedQuery(ModifiedSalesclerkFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ModifiedSalesclerk",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async modifiedSalesclerks(
    @common.Req() request: Request
  ): Promise<ModifiedSalesclerk[]> {
    const args = plainToClass(ModifiedSalesclerkFindManyArgs, request.query);
    return this.service.modifiedSalesclerks({
      ...args,
      select: {
        financedSales: {
          select: {
            id: true,
          },
        },

        id: true,
        newSalesclerkUserId: true,
        oldSalesclerkUserId: true,
        personalLoanId: true,
        updatedAt: true,
        updatedUserId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ModifiedSalesclerk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ModifiedSalesclerk",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async modifiedSalesclerk(
    @common.Param() params: ModifiedSalesclerkWhereUniqueInput
  ): Promise<ModifiedSalesclerk | null> {
    const result = await this.service.modifiedSalesclerk({
      where: params,
      select: {
        financedSales: {
          select: {
            id: true,
          },
        },

        id: true,
        newSalesclerkUserId: true,
        oldSalesclerkUserId: true,
        personalLoanId: true,
        updatedAt: true,
        updatedUserId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ModifiedSalesclerk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ModifiedSalesclerk",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateModifiedSalesclerk(
    @common.Param() params: ModifiedSalesclerkWhereUniqueInput,
    @common.Body() data: ModifiedSalesclerkUpdateInput
  ): Promise<ModifiedSalesclerk | null> {
    try {
      return await this.service.updateModifiedSalesclerk({
        where: params,
        data: {
          ...data,

          financedSales: data.financedSales
            ? {
                connect: data.financedSales,
              }
            : undefined,
        },
        select: {
          financedSales: {
            select: {
              id: true,
            },
          },

          id: true,
          newSalesclerkUserId: true,
          oldSalesclerkUserId: true,
          personalLoanId: true,
          updatedAt: true,
          updatedUserId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ModifiedSalesclerk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ModifiedSalesclerk",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteModifiedSalesclerk(
    @common.Param() params: ModifiedSalesclerkWhereUniqueInput
  ): Promise<ModifiedSalesclerk | null> {
    try {
      return await this.service.deleteModifiedSalesclerk({
        where: params,
        select: {
          financedSales: {
            select: {
              id: true,
            },
          },

          id: true,
          newSalesclerkUserId: true,
          oldSalesclerkUserId: true,
          personalLoanId: true,
          updatedAt: true,
          updatedUserId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
