/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsInt,
  IsEnum,
  IsDate,
  IsNumber,
} from "class-validator";
import { CashCountWhereUniqueInput } from "../../cashCount/base/CashCountWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumBankReceiptEstatusFicha } from "./EnumBankReceiptEstatusFicha";
import { EnumBankReceiptEstatusValidacion } from "./EnumBankReceiptEstatusValidacion";
import { Decimal } from "decimal.js";
import { EnumBankReceiptTipoDeposito } from "./EnumBankReceiptTipoDeposito";

@InputType()
class BankReceiptUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  autorizacion?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  banco?: string;

  @ApiProperty({
    required: false,
    type: () => CashCountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CashCountWhereUniqueInput)
  @IsOptional()
  @Field(() => CashCountWhereUniqueInput, {
    nullable: true,
  })
  cashCounts?: CashCountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  createdUserId?: number;

  @ApiProperty({
    required: false,
    enum: EnumBankReceiptEstatusFicha,
  })
  @IsEnum(EnumBankReceiptEstatusFicha)
  @IsOptional()
  @Field(() => EnumBankReceiptEstatusFicha, {
    nullable: true,
  })
  estatus_ficha?: "A" | "I";

  @ApiProperty({
    required: false,
    enum: EnumBankReceiptEstatusValidacion,
  })
  @IsEnum(EnumBankReceiptEstatusValidacion)
  @IsOptional()
  @Field(() => EnumBankReceiptEstatusValidacion, {
    nullable: true,
  })
  estatus_validacion?: "SV" | "I" | "C" | "CB" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaDeposito?: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaValidacion?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  folio?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  idBanco?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  montoDeposito?: Decimal;

  @ApiProperty({
    required: false,
    enum: EnumBankReceiptTipoDeposito,
  })
  @IsEnum(EnumBankReceiptTipoDeposito)
  @IsOptional()
  @Field(() => EnumBankReceiptTipoDeposito, {
    nullable: true,
  })
  tipo_deposito?: "V" | "T" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  validUserId?: number | null;
}

export { BankReceiptUpdateInput as BankReceiptUpdateInput };
