/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  BillingConceptCode as PrismaBillingConceptCode,
} from "@prisma/client";

export class BillingConceptCodeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BillingConceptCodeCountArgs, "select">
  ): Promise<number> {
    return this.prisma.billingConceptCode.count(args);
  }

  async billingConceptCodes<T extends Prisma.BillingConceptCodeFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.BillingConceptCodeFindManyArgs>
  ): Promise<PrismaBillingConceptCode[]> {
    return this.prisma.billingConceptCode.findMany<Prisma.BillingConceptCodeFindManyArgs>(
      args
    );
  }
  async billingConceptCode<T extends Prisma.BillingConceptCodeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.BillingConceptCodeFindUniqueArgs>
  ): Promise<PrismaBillingConceptCode | null> {
    return this.prisma.billingConceptCode.findUnique(args);
  }
  async createBillingConceptCode<T extends Prisma.BillingConceptCodeCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BillingConceptCodeCreateArgs>
  ): Promise<PrismaBillingConceptCode> {
    return this.prisma.billingConceptCode.create<T>(args);
  }
  async updateBillingConceptCode<T extends Prisma.BillingConceptCodeUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BillingConceptCodeUpdateArgs>
  ): Promise<PrismaBillingConceptCode> {
    return this.prisma.billingConceptCode.update<T>(args);
  }
  async deleteBillingConceptCode<T extends Prisma.BillingConceptCodeDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.BillingConceptCodeDeleteArgs>
  ): Promise<PrismaBillingConceptCode> {
    return this.prisma.billingConceptCode.delete(args);
  }
}
