/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  TimelyPayDiscount as PrismaTimelyPayDiscount,
} from "@prisma/client";

export class TimelyPayDiscountServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TimelyPayDiscountCountArgs, "select">
  ): Promise<number> {
    return this.prisma.timelyPayDiscount.count(args);
  }

  async timelyPayDiscounts<T extends Prisma.TimelyPayDiscountFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TimelyPayDiscountFindManyArgs>
  ): Promise<PrismaTimelyPayDiscount[]> {
    return this.prisma.timelyPayDiscount.findMany<Prisma.TimelyPayDiscountFindManyArgs>(
      args
    );
  }
  async timelyPayDiscount<T extends Prisma.TimelyPayDiscountFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TimelyPayDiscountFindUniqueArgs>
  ): Promise<PrismaTimelyPayDiscount | null> {
    return this.prisma.timelyPayDiscount.findUnique(args);
  }
  async createTimelyPayDiscount<T extends Prisma.TimelyPayDiscountCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TimelyPayDiscountCreateArgs>
  ): Promise<PrismaTimelyPayDiscount> {
    return this.prisma.timelyPayDiscount.create<T>(args);
  }
  async updateTimelyPayDiscount<T extends Prisma.TimelyPayDiscountUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TimelyPayDiscountUpdateArgs>
  ): Promise<PrismaTimelyPayDiscount> {
    return this.prisma.timelyPayDiscount.update<T>(args);
  }
  async deleteTimelyPayDiscount<T extends Prisma.TimelyPayDiscountDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TimelyPayDiscountDeleteArgs>
  ): Promise<PrismaTimelyPayDiscount> {
    return this.prisma.timelyPayDiscount.delete(args);
  }
}
