/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SmsMasivosApiLog as PrismaSmsMasivosApiLog,
} from "@prisma/client";

export class SmsMasivosApiLogServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SmsMasivosApiLogCountArgs, "select">
  ): Promise<number> {
    return this.prisma.smsMasivosApiLog.count(args);
  }

  async smsMasivosApiLogs<T extends Prisma.SmsMasivosApiLogFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SmsMasivosApiLogFindManyArgs>
  ): Promise<PrismaSmsMasivosApiLog[]> {
    return this.prisma.smsMasivosApiLog.findMany<Prisma.SmsMasivosApiLogFindManyArgs>(
      args
    );
  }
  async smsMasivosApiLog<T extends Prisma.SmsMasivosApiLogFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SmsMasivosApiLogFindUniqueArgs>
  ): Promise<PrismaSmsMasivosApiLog | null> {
    return this.prisma.smsMasivosApiLog.findUnique(args);
  }
  async createSmsMasivosApiLog<T extends Prisma.SmsMasivosApiLogCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SmsMasivosApiLogCreateArgs>
  ): Promise<PrismaSmsMasivosApiLog> {
    return this.prisma.smsMasivosApiLog.create<T>(args);
  }
  async updateSmsMasivosApiLog<T extends Prisma.SmsMasivosApiLogUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SmsMasivosApiLogUpdateArgs>
  ): Promise<PrismaSmsMasivosApiLog> {
    return this.prisma.smsMasivosApiLog.update<T>(args);
  }
  async deleteSmsMasivosApiLog<T extends Prisma.SmsMasivosApiLogDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SmsMasivosApiLogDeleteArgs>
  ): Promise<PrismaSmsMasivosApiLog> {
    return this.prisma.smsMasivosApiLog.delete(args);
  }
}
