/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumEstimateAspiraOtroProducto } from "./EnumEstimateAspiraOtroProducto";
import {
  IsEnum,
  IsOptional,
  IsInt,
  IsNumber,
  IsDate,
  ValidateNested,
  IsString,
} from "class-validator";
import { EnumEstimateAutorizaContacto } from "./EnumEstimateAutorizaContacto";
import { Decimal } from "decimal.js";
import { Type } from "class-transformer";
import { ItemWhereUniqueInput } from "../../item/base/ItemWhereUniqueInput";
import { EnumEstimatePlazo } from "./EnumEstimatePlazo";
import { EnumEstimateRechazoFinanc } from "./EnumEstimateRechazoFinanc";
import { WarehouseWhereUniqueInput } from "../../warehouse/base/WarehouseWhereUniqueInput";

@InputType()
class EstimateUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumEstimateAspiraOtroProducto,
  })
  @IsEnum(EnumEstimateAspiraOtroProducto)
  @IsOptional()
  @Field(() => EnumEstimateAspiraOtroProducto, {
    nullable: true,
  })
  aspira_otro_producto?: "N" | "S" | null;

  @ApiProperty({
    required: false,
    enum: EnumEstimateAutorizaContacto,
  })
  @IsEnum(EnumEstimateAutorizaContacto)
  @IsOptional()
  @Field(() => EnumEstimateAutorizaContacto, {
    nullable: true,
  })
  autoriza_contacto?: "N" | "S" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  createdUserId?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  desctoPagoOportuno?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  enganche?: Decimal;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaCotiz?: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  interesAnual?: Decimal;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  interesSemanalMultiplo?: Decimal;

  @ApiProperty({
    required: false,
    type: () => ItemWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ItemWhereUniqueInput)
  @IsOptional()
  @Field(() => ItemWhereUniqueInput, {
    nullable: true,
  })
  items?: ItemWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  montoPago?: Decimal;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  motivoRechazo?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombreCompletoCliente?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numPagos?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  observacionesCotizacion?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  pagoSemanalIdeal?: Decimal | null;

  @ApiProperty({
    required: false,
    enum: EnumEstimatePlazo,
  })
  @IsEnum(EnumEstimatePlazo)
  @IsOptional()
  @Field(() => EnumEstimatePlazo, {
    nullable: true,
  })
  plazo?: "S" | "Q";

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  precioLista?: Decimal | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productoInteres?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumEstimateRechazoFinanc,
  })
  @IsEnum(EnumEstimateRechazoFinanc)
  @IsOptional()
  @Field(() => EnumEstimateRechazoFinanc, {
    nullable: true,
  })
  rechazo_financ?: "N" | "S" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telefonoCliente?: string;

  @ApiProperty({
    required: false,
    type: () => WarehouseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WarehouseWhereUniqueInput)
  @IsOptional()
  @Field(() => WarehouseWhereUniqueInput, {
    nullable: true,
  })
  warehouses?: WarehouseWhereUniqueInput;
}

export { EstimateUpdateInput as EstimateUpdateInput };
